#!/bin/bash
#
# ../origipmi
#

cmdline=../origipmi

usagestr=$(
cat <<EOF

../origipmi
\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit
}

[ $# -gt 0 ] && usage

cd /usr/lib/modules/$(uname -r)/kernel/drivers/char/ipmi/

for f in $(ls -1 *.old); do
	fname=$(basename --suffix=.old $f)
	#
	# if we already saved the originals, leave them alone.
	#
	[[ -e "$fname".old ]] && mv -v $f $fname.ko
done

cd -

